# Generated by Django 3.2.15 on 2023-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='PATINENT_NAME',
            new_name='PATIENT_NAME',
        ),
        migrations.AlterField(
            model_name='result',
            name='USER_CHECK',
            field=models.CharField(choices=[('未', '未'), ('算定可', '算定可'), ('算定不可', '算定不可')], max_length=4),
        ),
    ]
